language: python
python:
- 3.7.9
install:
- pip install -r serenity_project/requirements.txt
before_script:
- python serenity_project/manage.py migrate
script:
- black --check .
- flake8 .
- cd serenity_project
- coverage run --source=serenity_project,app manage.py test
after_script:
  - coveralls

deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: "W2sLIQ4XnNET1DOjwZgPh6h0m9zfUgx9CkmLJmOZKXuTTIFgZ4vifvGIZBL6AgIh89H3pSwdy6oMYlyclEtAA7IA72ZvvlGJ7c65Na8yHRqnv33h8vBiWfrN4HtRyYe/QwUWHpGf1fhoIL2zpe/Fb0MWUpGUUmQ92EC6kyeN2zhzN4sgUbCMaDX84/x4AzBhb1YgXV7bma2OBghBlmCF9GYRhDb0ySBzAZrYv5rIqYC5t4DZMJvrrPVGorB1Fy0vco2+5HJJHcXpKvgsIZv124ff3I/rKO7b1UZ2bGfhs2iSK9EoRvSId72CKxzzBsBU6ci3VOC9uQHLqyDX5curJaSbvJuTk1pUUMpELDRZaFuuWr02XbRbi2ywQEhBvYTuPWnxotXTxfrF1GOPfteru4d5mMjzunc3/DmgPkVIC3Pa24a8n5wCsNOj/MSb0cqdnO5IRlWsmAFhN/pm5CP0QLBLtzYSf/pUgdf/RshQMhI6PMsXX1DEsPs3IwW19DY6sRepbVN8vgmuWk7wAWGsD/POqz5y5+ru60JYDF87wRP1Ts/Wlxrz9a4kxz6AqkMGDFxxuar7Dn9ahCiJ9lFdExmJdhkwA8J8+hzDgZhMXmaGvm6Eokg8Y1yXzl+0kYE60yAO3dy007pOzM+eURnajHEExyvS/otmoyhL73370wE="
  secret_access_key:
    secure: "jxQbaWS+S8WE9Ciayjq2nP24k6FdSiJz/BsFH5bq9DG1Nsk2X4YOxXRvkMzQdomqCM7lIsGP9nMlHoXrUxy/oC6vP4AzgS/3NniqasBoBRIO5qkj3/EGogWnHcHDqAaGAdpcK8xW3f35n/I58EXcc0woplEunKWQNqlqS45f5eud5zBUi/hND/QkN8IOWNQhQjW/tjn05cqmjBiznTbfm0PdgKrBuvdiNhXzEDP/EjEFAY3Lvk8B347hyBfm/hyFSSI4UU9LTOAkutvcceIkDzNfJ0LppqvjMElIkknzseKNPDo5asGp52CxiTtGhtJyTG/jrlHdRP0lVU7pJAdqZxfqtMErIimOLzIod3+3Gu4zXAtiaXZBPTAJ+I7deG2yn7cvberEjhi9QTz9ukV08sHxX+ZIbyUnp982CSvc0xqmnWM0419S2eJIMzcVsQ+OR19GMDoz/MXQSqSNKv/yX2/WY69YMoqejh6aAUOmMrDXmXj3fDQpUpAeWfuRTyzwvDngSsusPDnyVvpJwRTIDnSGTkzTWQqfTMgflGnpXCpe/KKeTZ1+YWL/Sm/jCih0VNyUi/d1ENsJl3G7Ppz/I59XbSBGZ4AmOj+XOPRZreuzTbPsgsrKUTrrpvoPzvrSrGIoGCuugEtiQ4RVEW43C115KMDmR5/nlvqHNJWG7pc="
  region: "us-west-2"
  app: "se-proj-main-1"
  env: "se-proj-main-env-1"
  bucket_name: "elasticbeanstalk-us-west-2-915847908622"
  on:
    all_branches: true

notifications:
  slack: gcivil-nyu:OjvKzBFGWm6Zr6Ro0Y1D7gfh