language: python
python:
- 3.7.9
install:
- pip install -r serenity_project/requirements.txt
before_script:
- python serenity_project/manage.py migrate
script:
- black --check .
- flake8 .
- cd serenity_project
- coverage run --source=serenity_project,app manage.py test
after_script:
  - coveralls

deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: "FKzG23/mYl8foxpqDWqBSB/fwfbIxMucK4X3lqI4J4E3OEKKpfR4lY8cCZIKm+8QmxGeJtYeb+aU7BTc6nbRzcvaxoNo4RnlSXWZkYj6r97rf8DSksy1eCF6ajaSD89rp8Dg0LN3xn08vdQBjQWHlGl4/Y+cd/w/Kn3U/PLGiyzmVZr6l6QxK3JjKLDlxZ+/uitUIRgQgx6dBXAkFvYzVkThoW1Us1Zd8hE6GCFR8Yrr5xt+mfPde6Y3vpo79pvnlQlr+M6I+nGSd/2utEJNStZxpGNzuW/qjkLgFD9MVbRgUvDWgax4Aia5U1BfBroTS6LU01ZRQZAYmUiVcVcrRhWicPwxR7F0E1XVhrRqIGZcbd5Vq66PcZWhYLPsqBdwn0DaqOaRU1Sq8hZBWF/rGZ7NCr/CX6MYvZL3lqO95i4C6YeDB7Hy/w0Y/GSPX/HqMfhh7BVQxeZMBPKIQuWsTTtuKxH+vebDTFKJQheGHjUBgxmswPwbk7jGUHOyvynfDd9OrtNg4bMWWUJX1PAuIRr3R3kte3H/WwVQRTT0OPMdK6F86bJvLbc4SSx7MP7ApJuY5ZE9n2caT+4OuFkp1PecXw8j+2mVoc0Yhx5LnL/7p+lsphPo6P2it94kwbSOrJcUHyLfcXVysxB4P2hq576jbV6wredbi8PUe9Gn/qI="
  secret_access_key:
    secure: "X0GUsz2Vd/isQpVXvdtC4hLHoEvpmw4sEZqFfqv/vPYLK/llsEBWtHYLt9HqExB51os6LHuF0oAco0b+quAVndijAB0J82s6d3GadvCnOgAYkqNHnUi1gLBpn8gikG1oLJGut6E4OuIqWnVUqdWKkv4VU/zVdbtZy5KnuieF4+PsD/JZrRQXgNY0rU1Vj+2NIY2LOnndhfPzqX8oWOJSlybVI8oxShVetCw1Y2m4xB9Zq3p1tBFtSKTibb/7d/Zky4Cv4wqiNfvrZc1oeXckHYedwfXQ/tldvjjf6bgO9mxSFPY5toS99fcKMk/ba9e8PUpMPBqXBmjypw4I8zCM5Fu92AtxKSexbO88m8xBsDuy9ZXUXDzGV/cLsodlgFhRs17XOsmIDUp9KPnSDHkPUARHOVFtTPTCS01tgQXsspIYVbf67lFBRMEaroCbAGN4mqrxt8o7tw3YHC6V8wB+aqlKn40YboraRN6SvQLGPPJeg0iwTnMJHWxfuIaP9Wd12qPKO9KfjSsw/5xA+bNjQgvBYwcmPkm0Ibp6X54AnK3f76yUCP/34IoU2GT42zvrk9/PdwGmQ7BJsA0INNEFfYMmIIdeyTxPAawt0OWoRQfVq3+u9mOmR/5NsFp9xvvs07q8w9L3yNse8uVg7uBpTQtPD3xbZCz6i73/e2ZnUcI="
  region: "us-west-2"
  app: "se-proj-main"
  env: "se-proj-main-env"
  bucket_name: "elasticbeanstalk-us-west-2-108396744441"
  on:
    all_branches: true

notifications:
  slack: gcivil-nyu:OjvKzBFGWm6Zr6Ro0Y1D7gfh