language: python
python:
- 3.7.9
install:
- pip install -r serenity_project/requirements.txt
before_script:
- python serenity_project/manage.py migrate
script:
- black --check .
- flake8 .
- cd serenity_project
- coverage run --source=serenity_project,app manage.py test
after_script:
  - coveralls

notifications:
  slack: gcivil-nyu:OjvKzBFGWm6Zr6Ro0Y1D7gfh
