language: python
python:
- 3.7.9
install:
- pip install -r serenity_project/requirements.txt
before_script:
- python serenity_project/manage.py migrate
script:
- black --check .
- flake8 .
- cd serenity_project
- coverage run --source=serenity_project,app manage.py test
after_script:
  - coveralls

deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: "mkOTfaNpx9i2s4zuhksNksN+fnVqFPopnaKqTQdSa7o+y/WGatS/eAnvj+1hc3NpWfaHNR2ckdqLRViBUmCiyQfGHLEBVqQMA0YsSXHlppA9H5yQT5J1HIrVM0F8fDA6hzSz+Mw/HR4JOw0oSFctkc/k4nohgz2gWetk0MqCMq7uZi7m1IPegfFHhk+VhqMfQfrprbXDlt/2zy9O3ILQYW8EAP/qLZgkaIy98g8nD0l+wy4xnIHLpyvdb2IYmfuZJrSEbikwEIs7rFHsO5F2JLEe6WpSC1/26wHBWttC3BmTujFq3RIPhuRFlaWelQ7IvMODUiqSXm0JCadT6Zc9NX9UBYYZkHer5xDFPSlocN4Jg1cpnQQbVtFQoj2oRF5RwincNrHqxaG2kZczhXtrTfa6TewAViFrGqn9VtW90K2otu9v/oV0d6wwj/ycn3Jf0MsF65wXcwp8VlwkMS28LCzi2cJfLLSpRYm3MhRynsjyu0AJeCMFl4PpaTr7MGdU03I+ucm64R0MUs/anmpsc8u7gHAAkeZnxk0xREwXtAyM/G+oFzCAO9mjnP3ICTctxxplQQKB52ttFtT9Ob7UC6AjxIWEbZ39K1SOGIJP1olVUoxQgNPVIZrck2bcnY+IWQEgP8l7vDIYW4h48Zq11ee63+P0sf4Xq+obIYNcg7s="
  secret_access_key:
    secure: "SVTwpNqA3ISOfeyDtVr8BOZfgDdwFlOT0+De9/j0EsIdFlfXTaB0IhRGiwka85s+JFUmkzhievia01Ib+1vAShlS0yigogE7T2yOg0pW32PEhIt7bMT1TXgAiHAtC/KkuTuLI6fxBwvULtgfLyecz6Se44jQ+ZC9xxWzj7vsOrfzTV2Jq2zrKMwT1tFokAZSAhTqAoF5LChenNTSVOO2sV+P4tYLU6oKmuAx136QA/22+sYZnhb5hbLvsRlkhes1HDa80I71Km+UM4BtG210iKknn/bjelfJZLJf8twgeRKxRGJYFKbIV7mMuT4CA2ejRuRzVgvPjUOubq348x45HD/6HafeCPbcGqlK8WxVfl079Nw2e8bPez4gWcXTlacNFuhcpEYOzf20dITMzVAsTdJLti7ykSF2h05x4Cgm/tqaV89pjFXheCjDtjnDN2KyxXEnNQk5BAiap3fS1cuw7BoxO43gPJa5woehHXN6CM9MrJP4LZHu8120cdgpFIvm8hMYJDAXbLmGK4oxUyZqKqlKPJFGTkHcdZT8gu/H9J/SESJY9aoQBkPvd3geffftr3ZFxNo2r0owV7wNVSxfu33lUun+PGWNpVvdxx6W74oabgULxN00tOT2cNOsxb+gH2/9IJ+WWzmCnMKyI6NCXzoMIh6cNalPDnaXg/ouvBQ="
  region: "us-west-2"
  app: "se-proj-main"
  env: "se-proj-main-env"
  bucket_name: "elasticbeanstalk-us-west-2-328602044501"
  on:
    all_branches: true

notifications:
  slack: gcivil-nyu:OjvKzBFGWm6Zr6Ro0Y1D7gfh