language: python
python:
- 3.7.9
install:
- pip install -r serenity_project/requirements.txt
before_script:
- python serenity_project/manage.py migrate
script:
- black --check .
- flake8 .
- cd serenity_project
- coverage run --source=serenity_project,app manage.py test
after_script:
  - coveralls

deploy:
  provider: elasticbeanstalk
  access_key_id:
    secure: "QX272XmdonftapvnXcW22FN1xszDgNBbI8j3ZqO340bF+zk0dwCmu3X2FjTQ5aR5AHFBOEiXzJ8vIW7m/r5QFahp7S1E70DLB+e3dqNIjIjt30lj6GnT085LFFmpr9eSBfYBqdb+vSZ4aN33XBMj3g5aLRG8/LfsKAcbgH36McVFUQisaIfnoYsZVaN0cT/ruMKxm/nTsnf0xNyjjtmgIS1SuaGyhcDIDdSRlskDhF1tg3SMmnWj/ge9k0SOgWN07goTzWqlaFKOLu+zDVFTEQQiKbMuGeht5/7D7Zd1eDh3pK52Eohh3PqfqLPshMXjPgc4MW66+hYTa8+SyNRqmpLbEfXscjV5MqG9FdSNrypnKRW0hbl6yVH4Q8Ny+uGXDUHvCAzlBNLgrdJ97gUHK8fdHYAstiIN4JvhMhMZEKDM/sV59qBgEj0cU7eyodURG79Do0zTLYTNM+JKOFvX/HSBdDWSJDbDnJ7YdyZbbn6FC5jS1o0z0u6ghIGKxpNrhLNBuIDd8WhiB0hZ/Yn/sDEoqKXPjoYZj5TcT0bPyo1X0c4M/hmiJ7fzsFzof+gAGZMHvhsTVHCVytCIuLF93K0iNLm245yDUFZ3hbhXNbnP1Xf0rw6MY5aNk5kc38ZCFXhOMj0UBFHRoeAfNsKhJV76pZXYyoNobY6LegJhrNw="
  secret_access_key:
    secure: "IFrKb9+Kq+ACr2FUqeLRA/6ZaH2tfS+HGDpylyt2otHyyAdnHkRual2nNA4t/ZijJ58q4bCQDzbRNEhTWE7o0hX408VJBVYGAB6ffpzC5/miUfUpHcc1/pwKY8bhOpo3VIQgoZnDkapZuHQZzRE0p8hNX1Ymmps8RCvvRiGi84g5JR2i5ZNzx+oPWD+ez69BsFESQFv8bIzsd16Mbkm5wP0mqjdHPRVbYHUSILfgyThOU5ZIiwrr+xKswgKFil7SQT5CiAHaGsimlKLSrc79cBHKYSuZK0xLe+5JLsswBzCZj8ZmehDkYfUtFlYCH7Q58EG2AdvAFck9aR1O22+ojj+39sgyUZKFMiEglkfD0cX2MuxYlsqdDEGrbTV5uH09JhHw94HJbiLA2Tyvd7mpRhEFMwCptyan73TyACwoyuIzzVxckFQg6wb1LLDAtrk5IACI8DvQIR72SnUtZ8fL/QlXWtU+YITXyBNYztJVih6tjZDESQ4/m2a1MkenY5Ga3i2Qlm+zTx5KCFXnmHFbS2xxcnNYzPQ1Cg5QiCD367EhZ4a8juY/+Y80CVqLFbLgtot/gXxTCBD0DvwxeC/3kaLOcEgdoscmffSHX8vQAV49MtnJ22Ln5WBvEvXQStg1dQdXhrx0lZzlLuuLZT1bmwYIdkeO+wM142JJTav5SBo="
  region: "us-west-2"
  app: "se-proj-main1"
  env: "se-proj-main-env1"
  bucket_name: "seproj-main1"
  on:
    all_branches: true

notifications:
  slack: gcivil-nyu:OjvKzBFGWm6Zr6Ro0Y1D7gfh